ApexClass/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <label>BillToContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Conatct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ApexClass/src/classes/ValidateOpportunityClass.cls
public class ValidateOpportunityClass {
    public static void opportunityUpdateValidation(List<Opportunity> ol){
        for(Opportunity o : ol){
            if(o.BillToContact__c!=null && o.Manager__c==null){
                System.debug(o.BillToContact__c);
                Contact cc = [select id, name,Account.id from Contact where (id = :o.BillToContact__c AND account.id!=null)];
                o.Manager__c = cc.Account.id;
            }
        }     
    }  
}