ApexClass/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <label>BillToContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Conatct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ApexClass/src/classes/OpportunityManagement.cls
public class OpportunityManagement {
    public static void PopoulateManagerForOpportunity(List<Opportunity> opportunities)
    {
        for(Opportunity opportunity : opportunities)
        {
            if(opportunity.BillToContact__c!=null 
               && opportunity.Manager__c==null)
            {
                Contact contact = [select id, name, Account.id from Contact where id = :opportunity.BillToContact__c];
                opportunity.Manager__c = contact.Account.id;
            }
        }     
    }  
}