WebServiceAssignment/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualForceAssignment_1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebServiceAssignment/src/classes/StudentSiteController.cls
public class StudentSiteController {
   public static List<Student__c> students{ get; private set;}
   public static Student__c studentInfo{ get; set;}
   public StudentSiteController (){
   }
    
   public static  List<SelectOption> options { get{    
       students = new List<Student__c> ([SELECT Id,Name FROM Student__c]);
       options = new List<SelectOption> ();
       for(Student__c student : students) {
           options.add(new SelectOption(student.Id,student.Name));
       }
       return options;
   } set;}
   
   @RemoteAction
   public static Student__c getStudent( Id selectedId ){
       studentInfo = [SELECT Id, FirstName__c, LastName__c, Class__r.Name  FROM Student__c WHERE Id =:selectedId] ;
       return studentInfo ;
   }  
}