WebServiceAssignment/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <picklist>
            <picklistValues>
                <fullName>RAJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualForceAssignment_1/src/classes/ManageClassController.cls
public with sharing class ManageClassController {

    public Class__c classToUpdate { get; private set; }
    public String idToUpdate {get;set;}
    public boolean displayPopup {get; set;} 
    
    String query = 'Select Id, Name, fee__c, board__c From Class__c ';
    
    public ManageClassController(ApexPages.StandardController controller) {
    }
    
    public void saveClass() {  
        update classToUpdate;
        displayPopup = false;    
    }  
    
    public void deleteClass() { 
        classToUpdate = [select id,name,fee__C from Class__c where id = :idToUpdate];
        delete classToUpdate;
    }  
    
    public void ShowDataToEdit() { 
        classToUpdate = [select id, name, fee__c,board__C from Class__c where id = :idToUpdate];
        displayPopup = true;    
    }   

    public List<Class__C> getfindClasses() 
    {
        return Database.query(query); 
    }  
}