WebServiceAssignment/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <label>ClassTeacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Class_Teacher</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ValidationRuleAndWorkflow/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <picklist>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

ValidationRuleAndWorkflow/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Date Of Birth</description>
        <inlineHelpText>Date Of Birth</inlineHelpText>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ValidationRuleAndWorkflow/src/classes/Assignment_2_SOQL.cls
public class Assignment_2_SOQL {
    public static void SOQL(){
        List<Student__c> sl1 = [SELECT Name,DOB__c,Sex__c from Student__c where LastName__c like 'S%'];
      	List<Student__c> sl2 = [SELECT Name from Student__c where Class__r.Name like 'X%'];
        List<Student__c> sl3 = [Select Name,Class__r.Name from Student__c];
        List<Class__c> sl4 = [SELECT Id, Name,(SELECT Name FROM Students__r) FROM Class__c];
        List<Student__c> sl5 = [Select name,DOB__c,Sex__c from Student__C where Class__r.ClassTeacher__r.Name like 'N%'];
		List<Student__c> sl6 = [Select Name,DOB__c,Sex__c from Student__c where DOB__c > 2000-12-31];
        List<Lead> sl7 = [Select name From Lead where LastModifiedDate = THIS_MONTH];
		List<Class__c> sl8 = [SELECT Id, Name,(SELECT Name FROM Students__r where name like 'S%') FROM Class__c];
        List<Contact> sl9 = [Select firstName, LastName from Contact where Subjects__c INCLUDES ('Hindi;English')]; 
       	List<Student__C> sl10 = [Select firstName__c, LastName__c from Student__C where Class__r.ClassTeacher__r.Subjects__c INCLUDES ('Hindi','English')];
    }
}