ValidationRuleAndWorkflow/src/objects/Account.object
<CustomObject>
</CustomObject>

GovernorLimitAssignment/src/objects/Account.object
    <fields>
        <fullName>ContactIDs__c</fullName>
        <label>ContactIDs</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>

WebServiceAssignment/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <picklist>
            <picklistValues>
                <fullName>RAJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualForceAssignment_1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ApexClass/src/classes/ClassDetails.cls
public class ClassDetails {
    public static List<Student__c> getClassDetails(String classId){
       List<Student__C> studentList = new List<Student__C>();
        studentList = [Select name from Student__c where class__r.id = :classId];
        return studentList;
    }
    
    public static Map<Class__c, List<Student__c>> getMapOfClassAndStudent(){
        Map<Class__c,List<Student__c>> classMap = new Map<Class__c,List<Student__c>>();
        List<Student__c> studentList = new List<Student__c>();
        for(Class__c classes : [Select id, name, board__c from Class__C]){
           studentList = [Select id from Student__c where class__r.id = :classes.id];
            classMap.put(classes, studentList);
        }
        return classmap;
    }
    
    public static Integer numberOfWorkingDays(Date date1, Date date2){
        /*Date d = Date.newInstance(1900, 1, 7);
        Integer noOfdays = d.daysBetween(date1);
      	Integer day = Math.mod(noOfdays, 7);*/
        Integer dd = date1.daysBetween(date2);
        Integer nw = dd/7;
        Integer ed = Math.mod(dd,7);
        Integer addDay = nw*7;
        date1 = date1.addDays(addDay);
        
        for(Integer i=1; i<=ed; i++){
             Date d = Date.newInstance(1900, 1, 7);
        Integer noOfdays = d.daysBetween(date1.addDays(i));
      	Integer day = Math.mod(noOfdays, 7); 
            if(day==1 || day==2 || day==3 ||day==4||day==5){ 
                addDay++;
            } 
        }
         return addDay;      
    }
    
     public static void insertContactId(String contactId){
     	Contact c = [select Account.id,Account.ContactIDs__c from Contact where id = :contactId];
         String value = '';
         if(c.Account.ContactIDs__c != null){
             
         }else{
             for(Contact cl : [Select id from Contact where Account.id = :c.AccountId]){
                 value+=cl.id+',';
             }
         }
         Account a1 = new Account();
         a1.name='n';
        
         System.debug(value);
         a1.ContactIDs__c = value;
         insert a1;
     }
}